from . import hospital_person
from . import hospital_doctor
from . import hospital_patient
from . import hospital_diagnosis
from . import hospital_disease_directory
from . import hospital_sample_type
from . import hospital_lab_test
from . import hospital_visit
from . import hospital_schedule
from . import hospital_symptom
